### ISSUE TITLE
JD-GUI crashes on Mojave

### ISSUE THREAD

**Issue by agGitHub** [java-decompiler/jd-gui#221]
Hi,

I try to launch JD-GUI on Mojave but the icon "jumps" a few times in my launcher and then the app does not launch.

How to solve this issue?

Regards.

**Comment by SiyangHe2017** [comment]
same problem

**Comment by laykinx** [comment]
I have too.

**Comment by SiyangHe2017** [comment]
> I have too.

I have already fixed it

**Comment by Colcode** [comment]
JD-GUI-->right click-->Contents-->Resources-->Java-->jd-gui-1.4.0.jar double click.

**Comment by agGitHub** [comment]
> JD-GUI-->right click-->Contents-->Resources-->Java-->jd-gui-1.4.0.jar double click.

Does not solve my problem. I can't launch the app with this procedure. Anybody has a solution ? Thanks.

**Comment by emmanue1** [comment]
Same problem with JD-GUI 1.5.0 ?
Does "java -jar jd-gui-x.y.z.jar" work ?
Do you have traces on console ?
Is your problem similar to #147?

**Comment by agGitHub** [comment]
Great. The update to 1.5 solves the issue! Thanks.

**Comment by java-decompiler** [comment]
Great. I close this issue.
